# Generated by Django 6.0.5 on 2026-05-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('speaker', models.CharField(max_length=255, verbose_name='Disertante')),
                ('date', models.CharField(max_length=100, verbose_name='Fecha')),
                ('time', models.CharField(max_length=100, verbose_name='Hora')),
                ('department', models.CharField(choices=[('Magistral', 'Magistral'), ('Básicas', 'Básicas'), ('Civil', 'Civil'), ('Industrial', 'Industrial'), ('Sistemas', 'Sistemas'), ('Química', 'Química'), ('Eléctrica', 'Eléctrica'), ('Mecánica', 'Mecánica')], max_length=50, verbose_name='Departamento')),
                ('capacity', models.PositiveIntegerField(verbose_name='Cupos')),
                ('target_year', models.CharField(choices=[('Todos los años', 'Todos los años'), ('1er año', '1er año'), ('2do año', '2do año'), ('3er año', '3er año'), ('4to año', '4to año'), ('5to año', '5to año'), ('1ero y 2do', '1ero y 2do año'), ('4to y 5to', '4to y 5to año')], default='Todos los años', max_length=50, verbose_name='Año de Cursada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='talk_images/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Charla',
                'verbose_name_plural': 'Charlas',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('legajo', models.CharField(max_length=20, verbose_name='Legajo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('attended', models.BooleanField(default=False, verbose_name='Asistió')),
                ('token', models.CharField(max_length=36, unique=True, verbose_name='Token')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='charlas.talk')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
