# Generated by Django 4.2.30 on 2026-05-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Ubicación"
            ),
        ),
    ]
