# Generated by Django 4.2.30 on 2026-05-20 17:25

import charlas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0002_talk_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("total", "Total de charlas"), ("por_dia", "Por día")],
                        default="total",
                        max_length=10,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "minimo",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Mínimo de charlas"
                    ),
                ),
                (
                    "requiere_magistral",
                    models.BooleanField(
                        default=False, verbose_name="Requiere magistral"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, verbose_name="Configuración activa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuración de Certificados",
                "verbose_name_plural": "Configuraciones de Certificados",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("dni", models.CharField(max_length=20, verbose_name="DNI")),
                ("legajo", models.CharField(max_length=20, verbose_name="Legajo")),
                ("correo", models.EmailField(max_length=254, verbose_name="Correo")),
                (
                    "codigo",
                    models.CharField(
                        default=charlas.models.generate_cert_code,
                        max_length=8,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificados/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "emitido_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Emitido el"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="charlas.certificateconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
            },
        ),
    ]
