# Generated by Django 4.2.30 on 2026-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0003_certificateconfig_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("enviados", models.PositiveIntegerField(default=0)),
                ("errores", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Job de Emisión",
                "verbose_name_plural": "Jobs de Emisión",
            },
        ),
    ]
