# Generated by Django 4.2.30 on 2026-05-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0004_emissionjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organizacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "instalaciones",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "comunicacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("tematicas", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comentario_general", models.TextField(blank=True, default="")),
                (
                    "feria_empresas_puntuacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("feria_empresas_contacto", models.BooleanField(blank=True, null=True)),
                ("feria_empresas_comentario", models.TextField(blank=True, default="")),
                (
                    "feria_laboratorios_puntuacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "feria_laboratorios_conocia",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "feria_laboratorios_comentario",
                    models.TextField(blank=True, default=""),
                ),
                ("completada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="charlas.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuesta",
                "verbose_name_plural": "Encuestas",
            },
        ),
        migrations.CreateModel(
            name="TalkRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion_disertante",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "puntuacion_contenido",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comentario", models.TextField(blank=True, default="")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_ratings",
                        to="charlas.survey",
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="charlas.talk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Puntuación de Charla",
                "verbose_name_plural": "Puntuaciones de Charlas",
                "unique_together": {("survey", "talk")},
            },
        ),
    ]
