# Generated by Django 4.2.30 on 2026-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0005_survey_talkrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateconfig",
            name="descarga_habilitada",
            field=models.BooleanField(
                default=False, verbose_name="Descarga habilitada"
            ),
        ),
        migrations.AddField(
            model_name="certificateconfig",
            name="mensaje_bloqueado",
            field=models.TextField(
                default="La descarga de certificados aún no está habilitada. Te avisaremos por correo cuando esté disponible.",
                verbose_name="Mensaje cuando está bloqueado",
            ),
        ),
    ]
