# Generated by Django 4.2.30 on 2026-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0006_certificateconfig_descarga_habilitada_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="comentario_general",
            new_name="a_mejorar",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="feria_empresas_contacto",
            new_name="asistio_feria_empresas",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="feria_laboratorios_conocia",
            new_name="asistio_feria_laboratorios",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="feria_empresas_comentario",
            new_name="lab_interesante",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="feria_laboratorios_comentario",
            new_name="lo_mejor",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="comunicacion",
            new_name="organizacion_general",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="feria_empresas_puntuacion",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="feria_laboratorios_puntuacion",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="instalaciones",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="organizacion",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="tematicas",
        ),
        migrations.AddField(
            model_name="survey",
            name="anio_cursada",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="aporte_formacion",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="carrera",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="survey",
            name="conocio_proyectos",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="evaluacion_feria_empresas",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="evaluacion_feria_laboratorios",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="evaluacion_general",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="interes_tematicas",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_acreditacion",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_colaboradores",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_disertantes",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_espacios",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_horarios",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_informacion",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_inscripcion",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="matriz_variedad",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="survey",
            name="mejoras_feria_empresas",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="mejoras_feria_laboratorios",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="proxima_edicion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="stands_interesantes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="survey",
            name="utilidad_feria_empresas",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
