# Generated by Django 4.2.30 on 2026-05-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0007_rename_comentario_general_survey_a_mejorar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateconfig",
            name="dias_reclamo",
            field=models.PositiveIntegerField(
                default=7, verbose_name="Días para reclamar"
            ),
        ),
        migrations.AddField(
            model_name="certificateconfig",
            name="dias_respuesta",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Días para responder"
            ),
        ),
        migrations.CreateModel(
            name="Reclamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=20, verbose_name="DNI")),
                ("legajo", models.CharField(max_length=20, verbose_name="Legajo")),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "carrera",
                    models.CharField(
                        choices=[
                            ("Industrial", "Ingeniería Industrial"),
                            ("Sistemas", "Ingeniería en Sistemas de Información"),
                            ("Mecánica", "Ingeniería Mecánica"),
                            ("Química", "Ingeniería Química"),
                            ("Civil", "Ingeniería Civil"),
                            ("Eléctrica", "Ingeniería en Energía Eléctrica"),
                        ],
                        max_length=50,
                        verbose_name="Carrera",
                    ),
                ),
                ("correo", models.EmailField(max_length=254, verbose_name="Correo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("asistencia", "Fui pero no se registró mi presente"),
                            ("justificacion", "Ausencia justificada"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            (
                                "no_registrado",
                                "Fui a una charla pero no se me registró el presente",
                            ),
                            ("trabajo", "No pude asistir a las jornadas por trabajo"),
                            (
                                "no_cursa",
                                "No asistí a charlas de un día porque no curso ese día",
                            ),
                            (
                                "superposicion",
                                "El cambio de horario generó una superposición de charlas",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Motivo",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "dia",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Día"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reclamos/",
                        verbose_name="Adjunto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("ampliacion", "Ampliación solicitada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "resolucion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("charla", "Perdonar charla/s específica/s"),
                            ("dia", "Perdonar día/s completo/s"),
                            ("certificado_directo", "Emitir certificado directamente"),
                            ("asistencia", "Marcar asistencia como presente"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Resolución",
                    ),
                ),
                (
                    "nota_admin",
                    models.TextField(
                        blank=True, default="", verbose_name="Nota del administrador"
                    ),
                ),
                (
                    "nota_ampliacion",
                    models.TextField(
                        blank=True, default="", verbose_name="Solicitud de ampliación"
                    ),
                ),
                (
                    "respuesta_ampliacion",
                    models.TextField(
                        blank=True, default="", verbose_name="Respuesta de ampliación"
                    ),
                ),
                (
                    "dias_perdonados",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Días perdonados",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_cierre_reclamo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Cierre de reclamos"
                    ),
                ),
                (
                    "fecha_cierre_respuesta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Cierre de respuestas"
                    ),
                ),
                (
                    "charlas_perdonadas",
                    models.ManyToManyField(
                        blank=True, related_name="perdonadas", to="charlas.talk"
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamos",
                        to="charlas.talk",
                        verbose_name="Charla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reclamo",
                "verbose_name_plural": "Reclamos",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
