# Generated by Django 4.2.30 on 2026-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0008_certificateconfig_dias_reclamo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diploma", "Diploma de asistencia"),
                    ("constancia_parcial", "Constancia de participación parcial"),
                    ("constancia_justificacion", "Constancia de justificación"),
                ],
                default="diploma",
                max_length=30,
                verbose_name="Tipo",
            ),
        ),
    ]
