# Generated by Django 4.2.30 on 2026-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0009_certificate_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateconfig",
            name="encuesta_obligatoria",
            field=models.BooleanField(
                default=True, verbose_name="Encuesta obligatoria para descargar"
            ),
        ),
    ]
