# Generated by Django 4.2.30 on 2026-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0010_certificateconfig_encuesta_obligatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="attended_reclamo",
            field=models.BooleanField(
                default=False, verbose_name="Presente por reclamo"
            ),
        ),
    ]
