# Generated by Django 4.2.30 on 2026-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0011_registration_attended_reclamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamo",
            name="charlas_perdonadas_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Charlas perdonadas"
            ),
        ),
        migrations.AddField(
            model_name="reclamo",
            name="dias_perdonados_list",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Días perdonados"
            ),
        ),
    ]
