# Generated by Django 4.2.30 on 2026-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0012_reclamo_charlas_perdonadas_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateconfig",
            name="fecha_cierre_reclamo",
            field=models.DateField(
                blank=True,
                help_text='Fecha fija hasta la que se aceptan reclamos. Si se deja en blanco, se calcula automáticamente sumando "Días para reclamar" a la fecha de envío de certificados.',
                null=True,
                verbose_name="Fecha de cierre de reclamos",
            ),
        ),
        migrations.AlterField(
            model_name="certificateconfig",
            name="dias_reclamo",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Se usa solo si no se establece una fecha fija de cierre.",
                verbose_name="Días para reclamar",
            ),
        ),
    ]
