# Generated by Django 4.2.30 on 2026-06-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charlas", "0013_add_fecha_cierre_reclamo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre / Descripción"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Token"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Token de Dashboard",
                "verbose_name_plural": "Tokens de Dashboard",
                "ordering": ["-created_at"],
            },
        ),
    ]
